### ISSUE TITLE
 When I execute "eval_plm_wsp. sh" and "eval_wsp. sh", no results returned.

### ISSUE THREAD

**Issue by shall-learn** [Bahuia/HGNet#3]
I use the latest version and modify the kb_endpoint in the eval_plm_cwq.sh file and eval_cwq.sh file, but the results are still empty. If i add "--not_use_eg", they work fine

**Comment by shall-learn** [comment]
I use the query_interface.py to test the virtuoso service and the answers are right

**Comment by Bahuia** [comment]
Please make sure that you are using the virtuoso temporary files that we provide, as we involve queries to KG in EG.
In addition, it is possible that the model will be slow in executing the inference with EG due to the very large Freebase. Also, we are using a batch inference with batchsize set to 100 and the results are not output one by one. Take eval_cwq.sh for example, the first batch result will be output after about 1600 seconds.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/25888739/221130430-207af68a-7d89-4cf6-90ae-3efdcbe373ad.png">

**Comment by Bahuia** [comment]
Please make sure that you are using the virtuoso temporary files that we provide, as we involve queries to KG in EG.
In addition, it is possible that the model will be slow in executing the inference with EG due to the very large Freebase. Also, we are using a batch inference with batchsize set to 100 and the results are not output one by one. Take eval_cwq.sh for example, the first batch result will be output after about 1600 seconds.

![](https://user-images.githubusercontent.com/25888739/221130430-207af68a-7d89-4cf6-90ae-3efdcbe373ad.png)


> I use the latest version and modify the kb_endpoint in the eval_plm_cwq.sh file and eval_cwq.sh file, but the results are still empty. If i add "--not_use_eg", they work fine
